### ISSUE TITLE
Remote debugging has been terminated...

### ISSUE THREAD

**Issue by LarryEitel** [darul75/web-react#13]
Trying to run `npm run dev-server-debug`. Any ideas why I get the following response?

```
Remote debugging has been terminated with reason: Error: connect ECONNREFUSED. Is node running with --debug port 5858? Please re-attach to the new target.
```

**Comment by darul75** [comment]
it means another node_inspector process is already running on your host, kill it first

**Comment by darul75** [comment]
or in package.json change to use different debug port script line

"dev-server-debug": "node-debug --debug-brk build/server.js --debug --source-maps",

by

"dev-server-debug": "node-debug --debug-port 5859 --debug-brk build/server.js --debug --source-maps",

**Comment by darul75** [comment]
more options here https://github.com/node-inspector/node-inspector#options

**Comment by LarryEitel** [comment]
I don't have any other node apps running and I have tried another port with the same complaint. :(

**Comment by darul75** [comment]
no other process somewhere or firewall...look deep in process and kill all node process...or put --web-port option.

your browser will open automatically then and show debug mode for server side

**Comment by darul75** [comment]
I ll check tomorrow again

**Comment by LarryEitel** [comment]
I opened a port specifically. In task `manager/Details` I see `node.exe` in the list when I launch debug. I end the task and `node.exe` goes away. There does not seem to be any other node services running. Perhaps there is another way to determine that.

**Comment by darul75** [comment]
$ npm install -g node-inspector

**Comment by darul75** [comment]
README has to be rewritten, you are not the first to ask me ;)
