### ISSUE TITLE
WebStorm says that AppActions is not declared in imported module.

### ISSUE THREAD

**Issue by LarryEitel** [darul75/web-react#14]
'...\app\actions\AppActions.js' line 5:

`import AppActions from '../../actions/AppActions';`

WebStorm complains/suggests that `AppActions` `Default export is not declared in imported module.`

Just a curious message.

**Comment by darul75** [comment]
nice catch WebStorm is so strong, I will keep a look, may be caused by ES6 new features http://www.2ality.com/2014/09/es6-modules-final.html
but normally just a warning

**Comment by LarryEitel** [comment]
I figured that much. I am new at ES6 as well. I'm using your project to learn. :) I looked at many but yours includes the key pieces I'm looking for. Especially do I appreciate your $ajax example.

**Comment by darul75** [comment]
nice, me too I have learned by creating it, inspect, play, redo, good for both of us, you will build website quickly, enjoy Larry. do not hesitate

**Comment by LarryEitel** [comment]
Changing in AppActions
`module.exports = alt.createActions(AppActions);`

To:
`export default alt.createActions(AppActions);`

Makes WebStorm happier and doesn't seem to break anything.

Thoughts?

**Comment by darul75** [comment]
yes it is but I will add it later, thx Larry, or do not hesitate put a PR for it

**Comment by LarryEitel** [comment]
I am finding more places where same refactoring is required. Will submit a PR next chance.

**Comment by darul75** [comment]
:+1: 
sure a big refactoring is needed and it is difficult to make it alone :)

**Comment by LarryEitel** [comment]
Happy to help where/when I can. Are you open to discuss via Hangout/Skype?

**Comment by darul75** [comment]
I would like so much but it is blocked by our company proxy there  ;) otherwise on darul75@gmail.com when at home

**Comment by LarryEitel** [comment]
Hello @darul75, been MIA on this project because I have been focusing on `Redux` vs `Alt`.

**Comment by Fauzdar1** [comment]
Same issue with PHPStorm, messing things up here and then. Most of the times, it works and then suddenly stops working. Solution is to duplicate it and change the name, and it starts working again. Seriously, a mess.

I'm using it for multiple exports as 

    module.exports = {
    ...
    ...
    }
